## By sector feature selection:

In [45]:
import os
import pandas as pd

# Specify the path to your data folder
data_folder = r'C:\Users\matth\Risk-Lab-\data'

# Initialize an empty list to hold each company's transposed DataFrame
data_frames = []

# Traverse through all subfolders and files in the data folder
for root, _, files in os.walk(data_folder):
    for file in files:
        if file.endswith('.csv'):
            # Generate the full path for each CSV file
            file_path = os.path.join(root, file)
            
            # Read the CSV file into a DataFrame (assuming index is the date)
            df = pd.read_csv(file_path, index_col=0)
            
            # Transpose the DataFrame
            df_transposed = df.T
            
            # Prefix columns with the first four letters of the file name
            prefix = file[:4].upper()  # Uppercase prefix for consistency
            df_transposed.columns = [f"{prefix}_{col}" for col in df_transposed.columns]
            
            # Reset index and rename to include a unique Date column
            df_transposed.reset_index(inplace=True)
            df_transposed = df_transposed.rename(columns={'index': f'Date_{prefix}'})
            
            # Drop any duplicate columns in this individual DataFrame
            df_transposed = df_transposed.loc[:, ~df_transposed.columns.duplicated()]
            
            # Append the cleaned DataFrame to the list
            data_frames.append(df_transposed)

# Concatenate all DataFrames along the columns
combined_df = pd.concat(data_frames, axis=1)

# Consolidate date columns into a single 'Date' column
date_columns = [col for col in combined_df.columns if col.startswith('Date_')]
combined_df['Date'] = pd.to_datetime(combined_df[date_columns].bfill(axis=1).iloc[:, 0], errors='coerce')

# Drop the individual 'Date_' columns after creating a main 'Date' column
combined_df = combined_df.drop(columns=date_columns).set_index('Date').sort_index()

# Display the final combined DataFrame
print(combined_df)
# combined_df.to_csv('path_to_save_combined_data.csv')  # Uncomment to save to a CSV file

                                               QUAT_nan QUAT_Total Assets  \
Date
NaT   "=BDH($A$1, $B8, "19900101","","sort=a","dates...               NaN
NaT                                                 NaN               NaN
NaT                                                 NaN               NaN
NaT                                                 NaN               NaN
NaT                                                 NaN               NaN
...                                                 ...               ...
NaT                                                 NaN               NaN
NaT                                                 NaN               NaN
NaT                                                 NaN               NaN
NaT                                                 NaN               NaN
NaT                                                 NaN               NaN

     QUAT_  + Cash, Cash Equivalents & STI QUAT_    + Cash & Cash Equivalents  \
Date
NaT            CASH_CASH_EQTY_STI_DETAILED             BS_CASH_NEAR_CASH_ITEM
NaT                                    NaN                                NaN
NaT                                    NaN                                NaN
NaT                                    NaN                                NaN
NaT                                    NaN                                NaN
...                                    ...                                ...
NaT                                    NaN                                NaN
NaT                                    NaN                                NaN
NaT                                    NaN                                NaN
NaT                                    NaN                                NaN
NaT                                    NaN                                NaN

       QUAT_    + ST Investments QUAT_  + Accounts & Notes Receiv  \
Date
NaT   BS_MKT_SEC_OTHER_ST_INVEST                 BS_ACCT_NOTE_RCV
NaT                          NaN                              NaN
NaT                          NaN                              NaN
NaT                          NaN                              NaN
NaT                          NaN                              NaN
...                          ...                              ...
NaT                          NaN                              NaN
NaT                          NaN                              NaN
NaT                          NaN                              NaN
NaT                          NaN                              NaN
NaT                          NaN                              NaN

     QUAT_    + Accounts Receivable, Net QUAT_    + Notes Receivable, Net  \
Date
NaT          BS_ACCTS_REC_EXCL_NOTES_REC                 NOTES_RECEIVABLE
NaT                                  NaN                              NaN
NaT                                  NaN                              NaN
NaT                                  NaN                              NaN
NaT                                  NaN                              NaN
...                                  ...                              ...
NaT                                  NaN                              NaN
NaT                                  NaN                              NaN
NaT                                  NaN                              NaN
NaT                                  NaN                              NaN
NaT                                  NaN                              NaN

     QUAT_  + Unbilled Revenues QUAT_  + Inventories  ...  \
Date                                                  ...
NaT        BS_UNBILLED_REVENUES       BS_INVENTORIES  ...
NaT                         NaN                  NaN  ...
NaT                         NaN                  NaN  ...
NaT                         NaN                  NaN  ...
NaT                         NaN                  NaN  ...
...                         ...                  ...  ...
NaT                         NaN                  NaN  ...
NaT                         NaN                  NaN  ...
NaT                         NaN                  NaN  ...
NaT                         NaN                  NaN  ...
NaT                         NaN                  NaN  ...

                SO_Y_Nominations & Governance Oversight  \
Date
NaT                                                 NaN
NaT   #N/A Mandatory parameter [FIELDS] cannot be empty
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
...                                                 ...
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN

     SO_Y_Size of Nomination Committee  \
Date
NaT       SIZE_OF_NOMINATION_COMMITTEE
NaT                                NaN
NaT                                NaN
NaT                                NaN
NaT                                NaN
...                                ...
NaT                                NaN
NaT                                NaN
NaT                                NaN
NaT                                NaN
NaT                                NaN

     SO_Y_Num of Independent Directors on Nomination Cmte  \
Date
NaT                             NUM_IND_DIR_ON_NOM_CMTE
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
...                                                 ...
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN

     SO_Y_Number of Nomination Committee Meetings  \
Date
NaT                    NUM_OF_NOMINATION_CMTE_MTG
NaT                                           NaN
NaT                                           NaN
NaT                                           NaN
NaT                                           NaN
...                                           ...
NaT                                           NaN
NaT                                           NaN
NaT                                           NaN
NaT                                           NaN
NaT                                           NaN

     SO_Y_Nomination Committee Meeting Attendance Percentage  \
Date
NaT                      NOMINATION_CMTE_MTG_ATTEND_PCT
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
...                                                 ...
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN

                         SO_Y_Sustainability Governance  \
Date
NaT                                                 NaN
NaT   #N/A Mandatory parameter [FIELDS] cannot be empty
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
...                                                 ...
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN

     SO_Y_Verification Type SO_Y_Employee CSR Training  \
Date
NaT       VERIFICATION_TYPE      EMPLOYEE_CSR_TRAINING
NaT                     NaN                        NaN
NaT                     NaN                        NaN
NaT                     NaN                        NaN
NaT                     NaN                        NaN
...                     ...                        ...
NaT                     NaN                        NaN
NaT                     NaN                        NaN
NaT                     NaN                        NaN
NaT                     NaN                        NaN
NaT                     NaN                        NaN

                                            SO_Y_Tenure  \
Date
NaT                                                 NaN
NaT   #N/A Mandatory parameter [FIELDS] cannot be empty
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
...                                                 ...
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN
NaT                                                 NaN

     SO_Y_Board Duration (Years)
Date
NaT               BOARD_DURATION
NaT                          NaN
NaT                          NaN
NaT                          NaN
NaT                          NaN
...                          ...
NaT                          NaN
NaT                          NaN
NaT                          NaN
NaT                          NaN
NaT                          NaN

[173 rows x 22665 columns]

In [46]:
combined_df.head()

,QUAT_nan,QUAT_Total Assets,"QUAT_ + Cash, Cash Equivalents & STI",QUAT_ + Cash & Cash Equivalents,QUAT_ + ST Investments,QUAT_ + Accounts & Notes Receiv,"QUAT_ + Accounts Receivable, Net","QUAT_ + Notes Receivable, Net",QUAT_ + Unbilled Revenues,QUAT_ + Inventories,...,SO_Y_Nominations & Governance Oversight,SO_Y_Size of Nomination Committee,SO_Y_Num of Independent Directors on Nomination Cmte,SO_Y_Number of Nomination Committee Meetings,SO_Y_Nomination Committee Meeting Attendance Percentage,SO_Y_Sustainability Governance,SO_Y_Verification Type,SO_Y_Employee CSR Training,SO_Y_Tenure,SO_Y_Board Duration (Years)
Date,,,,,,,,,,,,,,,,,,,,,
NaT,"""=BDH($A$1, $B8, ""19900101"","""",""sort=a"",""dates...",NaN,CASH_CASH_EQTY_STI_DETAILED,BS_CASH_NEAR_CASH_ITEM,BS_MKT_SEC_OTHER_ST_INVEST,BS_ACCT_NOTE_RCV,BS_ACCTS_REC_EXCL_NOTES_REC,NOTES_RECEIVABLE,BS_UNBILLED_REVENUES,BS_INVENTORIES,...,NaN,SIZE_OF_NOMINATION_COMMITTEE,NUM_IND_DIR_ON_NOM_CMTE,NUM_OF_NOMINATION_CMTE_MTG,NOMINATION_CMTE_MTG_ATTEND_PCT,NaN,VERIFICATION_TYPE,EMPLOYEE_CSR_TRAINING,NaN,BOARD_DURATION
NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,#N/A Mandatory parameter [FIELDS] cannot be empty,NaN,NaN,NaN,NaN,#N/A Mandatory parameter [FIELDS] cannot be empty,NaN,NaN,#N/A Mandatory parameter [FIELDS] cannot be empty,NaN
NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
import os
import pandas as pd

# Specify the path to your data folder
data_folder = r'C:\Users\matth\Risk-Lab-\data'

# Initialize an empty list to hold each company's transposed DataFrame
data_frames = []

# Traverse through all subfolders and files in the data folder
for root, _, files in os.walk(data_folder):
    for file in files:
        if file.endswith('.csv'):
            # Generate the full path for each CSV file
            file_path = os.path.join(root, file)
            
            # Read the CSV file into a DataFrame
            df = pd.read_csv(file_path)
            
            # Remove the first five rows
            df_cleaned = df.iloc[5:]
            
            # Extract the date row (row 6) and drop the first value and the first two columns
            date_row = df_cleaned.iloc[0, 1:].values  # Remove the first value
            df_cleaned = df_cleaned.iloc[:, 2:]  # Remove the first two columns
            
            # Transpose the DataFrame
            df_transposed = df_cleaned.T
            
            # Ensure that date_row matches the length of the transposed DataFrame's index
            if len(date_row) != df_transposed.shape[0]:
                print(f"Warning: Length of date_row ({len(date_row)}) does not match transposed DataFrame index ({df_transposed.shape[0]}) for file {file}. Adjusting date_row to match.")
                date_row = date_row[:df_transposed.shape[0]]  # Trim or handle as needed

            # Set the date row as the index
            df_transposed.index = date_row
            
            # Prefix columns with the first four letters of the file name
            prefix = file[:4].upper()  # Uppercase prefix for consistency
            df_transposed.columns = [f"{prefix}_{col}" for col in df_transposed.columns]
            
            # Drop any duplicate indices in the transposed DataFrame
            df_transposed = df_transposed[~df_transposed.index.duplicated(keep='first')]
            
            # Append the cleaned DataFrame to the list
            data_frames.append(df_transposed)

# Concatenate all DataFrames along the columns
if data_frames:  # Check if there are DataFrames to concatenate
    combined_df = pd.concat(data_frames, axis=1)

    # Determine the largest index value
    largest_index_value = combined_df.index.max()

    # Create a new row called 'index' that matches the largest index value
    index_row = pd.Series([largest_index_value] * combined_df.shape[1], index=combined_df.columns, name='index')
    
    # Append the new index row to the DataFrame
    combined_df = combined_df.append(index_row)

    # Display the draft combined DataFrame
    print(combined_df)

    # Save the combined DataFrame to a CSV file if needed
    # combined_df.to_csv('path_to_save_combined_data.csv')
else:
    print("No DataFrames to combine.")

Warning: Length of date_row (1) does not match transposed DataFrame index (0) for file Quater_template.csv. Adjusting date_row to match.
Warning: Length of date_row (2) does not match transposed DataFrame index (1) for file Quater_template_Version-2.csv. Adjusting date_row to match.
Warning: Length of date_row (1) does not match transposed DataFrame index (0) for file Yearly_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (2) does not match transposed DataFrame index (1) for file Yearly_Template_Version-2.csv. Adjusting date_row to match.
Warning: Length of date_row (79) does not match transposed DataFrame index (78) for file GOOGL_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file GOOGL_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (43) does not match transposed DataFrame index (42) for file GOOGL_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file GOOG_Annual.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file GOOG_Quarter.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file META_Annual.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file META_Quarter.csv. Adjusting date_row to match.
Warning: Length of date_row (37) does not match transposed DataFrame index (36) for file META_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file META_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (31) does not match transposed DataFrame index (30) for file META_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file NFLX_Annual.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file NFLX_Quarter.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file NFLX_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file NFLX_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (41) does not match transposed DataFrame index (40) for file NFLX_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (36) does not match transposed DataFrame index (35) for file BYDDY_Annual.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file BYDDY_Quarter.csv. Adjusting date_row to match.
Warning: Length of date_row (43) does not match transposed DataFrame index (42) for file BYDDY_Segments_Annual_2003.csv. Adjusting date_row to match.
Warning: Length of date_row (53) does not match transposed DataFrame index (52) for file BYDDY_Segments_Quarter_2018.csv. Adjusting date_row to match.
Warning: Length of date_row (59) does not match transposed DataFrame index (58) for file TM_Annual.csv. Adjusting date_row to match.
Warning: Length of date_row (160) does not match transposed DataFrame index (159) for file TM_Quarter.csv. Adjusting date_row to match.
Warning: Length of date_row (41) does not match transposed DataFrame index (40) for file TM_Segments_Annual.csv. Adjusting date_row to match.
Warning: Length of date_row (41) does not match transposed DataFrame index (40) for file TM_Segments_Quarter_2013.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file TM_Segments_Quarter_2018.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file TM_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file Telsa_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file Tesla_Segments_ Annual.csv. Adjusting date_row to match.
Warning: Length of date_row (41) does not match transposed DataFrame index (40) for file Tesla_Segments_ Quarter_2009.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file Tesla_Segments_Quarter_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file TSLA_Annual.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file TSLA_Quarter.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file Costco_Quarter_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file COST_Annual_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (41) does not match transposed DataFrame index (40) for file COST_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file COST_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file COST_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (57) does not match transposed DataFrame index (56) for file COST_Segments_Yearly_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file PG_Annual_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file PG_Quarter_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file PG_Segments_Quarter_2005.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file PG_Segments_Quarter_2015.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file PG_Segments_Quarter_2025.csv. Adjusting date_row to match.
Warning: Length of date_row (49) does not match transposed DataFrame index (48) for file PG_Segments_Yearly_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file WMT_Annual_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file WMT_Quarter_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (47) does not match transposed DataFrame index (46) for file WMT_Segments_Quarter_2005.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file WMT_Segments_Quarter_2015.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file WMT_Segments_Quarter_2025.csv. Adjusting date_row to match.
Warning: Length of date_row (55) does not match transposed DataFrame index (54) for file WMT_Segments_Yearly_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file CVX_Annual.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file CVX_Quarter.csv. Adjusting date_row to match.
Warning: Length of date_row (49) does not match transposed DataFrame index (48) for file CVX_Segments_Annual_2000.csv. Adjusting date_row to match.
Warning: Length of date_row (31) does not match transposed DataFrame index (30) for file CVX_Segments_Quarter_2000.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file CVX_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file CVX_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (36) does not match transposed DataFrame index (35) for file PCCYF_Annual.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file PCCYF_Quarter.csv. Adjusting date_row to match.
Warning: Length of date_row (39) does not match transposed DataFrame index (38) for file PCCYF_Segments_Annual_2005.csv. Adjusting date_row to match.
Warning: Length of date_row (55) does not match transposed DataFrame index (54) for file PCCYF_Segments_Quarter_2007.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file PCCYF_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file XOM_Annual.csv. Adjusting date_row to match.

Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file XOM_Quarter.csv. Adjusting date_row to match.
Warning: Length of date_row (49) does not match transposed DataFrame index (48) for file XOM_Segments_Annual_2000.csv. Adjusting date_row to match.
Warning: Length of date_row (37) does not match transposed DataFrame index (36) for file XOM_Segments_Quarter_2000.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file XOM_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file XOM_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file BRK-B_Annual.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file BRK-B_Quarter.csv. Adjusting date_row to match.
Warning: Length of date_row (49) does not match transposed DataFrame index (48) for file BRK-B_Segments_Annual_2000.csv. Adjusting date_row to match.
Warning: Length of date_row (21) does not match transposed DataFrame index (20) for file BRK-B_Segments_Quarter_2001.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file BRK-B_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file BRK-B_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file JPM_Quarter_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (31) does not match transposed DataFrame index (30) for file JPM_Segments_Quarter_2001.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file JPM_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file JPM_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (47) does not match transposed DataFrame index (46) for file JPM_Segments_Yearly_2001.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file JPM_Yearly_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file V_Quarter_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (55) does not match transposed DataFrame index (54) for file V_Segments_Quarter_2008.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file V_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (39) does not match transposed DataFrame index (38) for file V_Segments_Yearly_2005.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file V_Yearly_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file JNJ_Quarter_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file JNJ_Segments_Quarterly_2001.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file JNJ_Segments_Quarterly_2005.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file JNJ_Segments_Quarterly_2015.csv. Adjusting date_row to match.
Warning: Length of date_row (51) does not match transposed DataFrame index (50) for file JNJ_Segments_Yearly_2001.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file JNJ_Yearly_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file LLY_Quarter_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (73) does not match transposed DataFrame index (72) for file LLY_Segments_Quarter_2006.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file LLY_Segments_Quarter_2015.csv. Adjusting date_row to match.
Warning: Length of date_row (45) does not match transposed DataFrame index (44) for file LLY_Segments_Yearly_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file LLY_Yearly_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file UNH_Annual_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file UNH_Quarter_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (39) does not match transposed DataFrame index (38) for file UNH_Segments_Quarter_2000.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file UNH_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file UNH_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (49) does not match transposed DataFrame index (48) for file UNH_Segments_Yearly_2000.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file CAT_Annual_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file CAT_Quarter_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (29) does not match transposed DataFrame index (28) for file CAT_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file CAT_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file CAT_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (47) does not match transposed DataFrame index (46) for file CAT_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file GE_Quarterly_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file GE_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file GE_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (41) does not match transposed DataFrame index (40) for file GE_Segments_Yearly_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file GE_Yearly_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file RTX_Quarter_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (31) does not match transposed DataFrame index (30) for file RTX_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file RTX_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file RTX_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (47) does not match transposed DataFrame index (46) for file RTX_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file RTX_Yearly_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file DD_Annual_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file DD_Quarter_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (69) does not match transposed DataFrame index (68) for file DD_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (17) does not match transposed DataFrame index (16) for file DD_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file MLM_Annual_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file MLM_Quarter_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (29) does not match transposed DataFrame index (28) for file MLM_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file MLM_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file MLM_Segments_Quarter_2024.csv. Adjusting date_row to match.

Warning: Length of date_row (47) does not match transposed DataFrame index (46) for file MLM_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file VMC_Annual_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file VMC_Quarter_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (29) does not match transposed DataFrame index (28) for file VMC_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file VMC_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file VMC_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (47) does not match transposed DataFrame index (46) for file VMC_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file CSX_Annual.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file CSX_Quarter.csv. Adjusting date_row to match.
Warning: Length of date_row (43) does not match transposed DataFrame index (42) for file CSX_Segments_Annual_2003.csv. Adjusting date_row to match.
Warning: Length of date_row (41) does not match transposed DataFrame index (40) for file CSX_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file CSX_Segments_Quarter_2009.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file CSX_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file NSC_Annual.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file NSC_Quarter.csv. Adjusting date_row to match.
Warning: Length of date_row (43) does not match transposed DataFrame index (42) for file NSC_Segments_Annual_2003.csv. Adjusting date_row to match.
Warning: Length of date_row (79) does not match transposed DataFrame index (78) for file NSC_Segments_Quarter_2003.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file NSC_Segments_Quarter_2013.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file NSC_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file UNP_Annual.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file UNP_Quarter.csv. Adjusting date_row to match.
Warning: Length of date_row (45) does not match transposed DataFrame index (44) for file UNP_Segments_Annual_2002.csv. Adjusting date_row to match.
Warning: Length of date_row (173) does not match transposed DataFrame index (172) for file UNP_Segments_Quarter_2003_ALL_To_Clean.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file UNP_Segments_Quarter_2004-2014_ALL_To_Clean.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file UNP_Segments_Quarter_2009-2018_ALL_To_Clean.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file UNP_Segments_Quarter_2014-2024_ALL_To_Clean.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file AMT_Annual_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file AMT_Quarter_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (5) does not match transposed DataFrame index (4) for file AMT_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file AMT_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file AMT_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (41) does not match transposed DataFrame index (40) for file AMT_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file EQIX_Annual_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file EQIX_Quarter_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (69) does not match transposed DataFrame index (68) for file EQIX_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file EQIX_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (41) does not match transposed DataFrame index (40) for file EQIX_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file PLD_Annual_Template.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file PLD_Quarter.csv. Adjusting date_row to match.
Warning: Length of date_row (47) does not match transposed DataFrame index (46) for file PLD_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file PLD_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (31) does not match transposed DataFrame index (30) for file PLD_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (34) does not match transposed DataFrame index (33) for file AAPL_Annual_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file AAPL_Quarter_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (15) does not match transposed DataFrame index (14) for file AAPL_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (79) does not match transposed DataFrame index (78) for file AAPL_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file AAPL_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (43) does not match transposed DataFrame index (42) for file AAPL_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file MSFT_Annual_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file MSFT_Quarter_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (37) does not match transposed DataFrame index (36) for file MSFT_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (41) does not match transposed DataFrame index (40) for file MSFT_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (41) does not match transposed DataFrame index (40) for file MSFT_Segments_Yearly_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file NVDA_Annual_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file NVDA_Quarter_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (77) does not match transposed DataFrame index (76) for file NVDA_Segments_Quarter_2015.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file NVDA_Segments_Quarter_2025.csv. Adjusting date_row to match.
Warning: Length of date_row (41) does not match transposed DataFrame index (40) for file NVDA_Segments_Yearly_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file DUK_Quarter_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (77) does not match transposed DataFrame index (76) for file DUK_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file DUK_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (41) does not match transposed DataFrame index (40) for file DUK_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file DUK_Yearly_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file NEE_Quarter_1990.csv. Adjusting date_row to match.

Warning: Length of date_row (31) does not match transposed DataFrame index (30) for file NEE_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file NEE_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file NEE_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (47) does not match transposed DataFrame index (46) for file NEE_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file NEE_Yearly_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (140) does not match transposed DataFrame index (139) for file SO_Quarter_1990.csv. Adjusting date_row to match.
Warning: Length of date_row (29) does not match transposed DataFrame index (28) for file SO_Segments_Quarter_2004.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file SO_Segments_Quarter_2014.csv. Adjusting date_row to match.
Warning: Length of date_row (81) does not match transposed DataFrame index (80) for file SO_Segments_Quarter_2024.csv. Adjusting date_row to match.
Warning: Length of date_row (47) does not match transposed DataFrame index (46) for file SO_Segments_Yearly_2023.csv. Adjusting date_row to match.
Warning: Length of date_row (35) does not match transposed DataFrame index (34) for file SO_Yearly_1990.csv. Adjusting date_row to match.

TypeError: '>=' not supported between instances of 'str' and 'float'

In [39]:
combined_df.head()

,Date_1,Date_2,Date_3,Date_4,Date_5,Date_6,Date_7,Date_8,Date_9,Date_10,...,SO_Y_294,SO_Y_295,SO_Y_296,SO_Y_297,SO_Y_298,SO_Y_299,SO_Y_300,SO_Y_301,SO_Y_302,SO_Y_303
0,None,None,None,None,None,None,None,None,None,None,...,NaN,NaN,NaN,#N/A Mandatory parameter [FIELDS] cannot be empty,#N/A Mandatory parameter [FIELDS] cannot be empty,NaN,NaN,#N/A Mandatory parameter [FIELDS] cannot be empty,#N/A Mandatory parameter [FIELDS] cannot be empty,NaN
1,NaN,None,None,None,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,None,None,None,None,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,None,None,None,None,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1031.500977,1.0,1256.516,1.0,1384.495,1.0,1578.456,1.0,1919.093,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN